- css/quizstyle.css
The file `css/quizstyle.css` was missing from the branch, now it should be added :)
> Added quiz styles

- css/quizstyle.css
- index.html
- js/index.js
put the 3 examples for potential question/answer styles
> Glottsi slider example

- data/01-07-20.json
- js/load.js
Refactored streamers data loading from google spreadsheet.
I put this in a new file 'load.js' as to not mess with the main index.js. 
'load.js' simply loads the google sheets data into a list of JSON objects which can then be used by other methods as need. I primarily did this because of how entangled the code was with itself. All the question, response, evaluate, table value, and slider code was mixed in with the loading code and I feel as more is added this could become a problem... harder to maintain when everything its tightly coupled. 
_Goal was to separate the concerns of (1) loading the data and (2) implementing data into app (e.i. feature, evaluate, question, sliders, etc). the `load.js` file fulfills concern (1)._
others changes
1.  streamers data structure
- previously, a map …
> Refactor data loading

- js/load.js
Added comments and created getUILabel method to get the UI label for a given spreadsheet json field
> comments + created getUILabel function

- backend/calculate_streamer_2.js
- public/index.html
- public/javascripts/index.js
- public/stylesheets/quizstyle.css
After the previous merge was created from glottsi/streamer-mtchmkr-postgres, there were additional changes in jinritv/streamer-mtchmkr-postgres. They are being merged in this pull request.
After this PR is merged, All streamer-mtchmkr-postgres repositories can be archived
> Merge extra changes from jinritv/streamer-mtchmkr-postgres

- backend/calculate_streamer_2.js
- db/alter_stream_time.sql
- models/streamers_stats.js
- public/index.html
- public/javascripts/index.js
New
- Scoring by matchtime, with timezone handled.
- Tooltip at frontend result for detailed score
- New DB field is required for stream start time store db/alter_stream_time.sql
- Logarithmic scoring for value that is close to input, configure SCORE_NEAR_THRESHOLD
- Randomized result if total score is the same.
Update
- Weighted question score (see ATTRIBUTE_POINTS backend/calculate_streamer_2.js)
- Fixed preferred language & content scoring.
- Fixed backend ordering of the result.
> [ysf-scoring-time] Scoring backend

- public/javascripts/localizations.js
Translated up to line 65.
do you guys like it?
> Translated Japanese

- backend/calculate_streamer_2.js
- db/db.sql
- models/chat_vibes.js
- models/models.js
- models/streamers_chat_vibes.js
- models/streamers_stats.js
- Handled maturity scoring
- Partial chat mode (fol only / sub only) handling (require db
migration)
- Handled chat vibes scoring
> [question-update] Additional question backend handling

- public/javascripts/html_helpers.js
- public/javascripts/index.js
- public/stylesheets/quizstyle.css
Added a little back button on the left side of the continue button on the quiz.
> Added Back Button to the quiz

- app.js
- routes/about.js
- views/about.ejs
- views/partials/footer.ejs
simple about page to be styled
> added about page

- public/stylesheets/about.css
update timeline styling as per design doc
> updated timeline styling

- app.js
- backend/localizations/translations/de-DE.json
- backend/localizations/translations/en-US.json
- backend/localizations/translations/fr-FR.json
- public/javascripts/about.js
- public/stylesheets/about.css
- routes/about.js
- routes/index.js
- views/about.ejs
- views/not_found.ejs
- views/partials/footer.ejs
- Updated 3 copyright texts in localizations\translations folder to "Copyright © 2021 JinriTV"
- Merged content in routes\about.js to index.js
- Added new public\javascripts\about.js as index.js loads the main page
- Updated about.ejs with header and footer
- Changed the Theme set check in routes\index.js to nullish coalescing operator
- Fixed missing equal sign for theme's string output in about.ejs and not_found.ejs "<%= Theme %>", updated the routes accordingly for passing the required json object
- Added new routing for submission and contribution page in routes\index.js
- Added hyperlinks to submission and contribution page in footer.ejs
- Added empty ejs files for submission and contribution page as placeholders
- Language change in about page is not working
- Theme change (e.g. …
> Minor enhancements with about page header/footer

- public/stylesheets/about.css
- public/stylesheets/submission.css
- views/about.ejs
- views/submission.ejs
Initial commits for submissions page. The page does not have much functionality yet
> Submission page

- public/javascripts/about.js
- public/javascripts/contribution.js
- public/javascripts/submission.js
- public/stylesheets/about.css
- public/stylesheets/contribution.css
- public/stylesheets/submission.css
- public/stylesheets/themes.css
- views/about.ejs
- views/contribution.ejs
- views/index.ejs
- views/partials/quiz_modal.ejs
- views/partials/scripts.ejs
- views/partials/stylesheets.ejs
- views/submission.ejs
- Added dark mode to contribution page, submission page, about page
- Fixed colors according to Figma's dark mode design
> Dark mode updates

- backend/quiz_questions.js
- public/stylesheets/about.css
- public/stylesheets/quizstyle.css
- public/stylesheets/submission.css
- public/stylesheets/themes.css
- views/about.ejs
- views/partials/header.ejs
- views/submission.ejs
- Updated css and media queries for mobile UI, should look better now on iPhone 5 / SE / 6 / 6 Plus / 7 / 7 Plus / 8 / 8 Plus / X
> Mobile Update

- public/stylesheets/themes.css
- views/partials/first_place_result.ejs
- views/partials/result_page.ejs
- Updated title, subtitle to h1 and h2 respectively
- Updated 1st place to use a wider container size
> Result page update

- backend/db/csv_db.js
Changing parseCategories to reflect that.
> Database was changed to use "/" for Categories.

- public/javascripts/index.js
- views/submission.ejs
- Updated the embed youtube URL into a youtube playlist URL
- Removed confetti on results page
> Minor Update

- public/stylesheets/quizstyle.css
Changed from px units to vmin for height and width of the background streamer images.
Added min-height and min-width to keep them from getting too small on mobile screens.
> Some sizing/position changes for the background streamer images.

- public/stylesheets/quizstyle.css
- views/full_page.ejs
- Added 'Add a Streamer' link to front page located below 'Find a Streamer' button
> UI updates
